package com.dstarlab.dstarcodegeneration.livedatagenerator

class LiveDataObjectBuilder(model: LiveDataGeneratorModel) {

    private val publicLiveDataName = model.fieldName.removePrefix("_")

    private val additionalContentTemplate = """
      
        /**
         * @see ${model.className}.${model.fieldName}
         */
        @Suppress("UNCHECKED_CAST")
        ${model.propertyModifiers}val ${model.className}.${publicLiveDataName} : ${model.type}
            get() {
                 val lvPrivate = javaClass.getDeclaredField("${model.fieldName}") 
                 lvPrivate.isAccessible = true 
                 val lv = lvPrivate.get(this) 
                 
                 return lv as ${model.type}
            }
        
    """.trimIndent()

    private val contentTemplate = """
// Generated by LiveDataGenerator (dstarcodegeneration module).
package ${model.pack}
        
import androidx.lifecycle.LiveData

$additionalContentTemplate
""".trimIndent()

    fun getDefaultContent() = contentTemplate
    fun getAdditionalContent() = additionalContentTemplate
}